# Graph QL file that is used for all of the typeDefs

# User typeDef
type User {
    _id: ID
    username: String! @unique
    email: String!
    password: String!
    avatar: String
    joinDate: String
    favorites: [Post]
}

# Post typeDef
type Post {
    _id: ID
    title: String!
    imageUrl: String!
    categories: [String]!
    description: String!
    createdDate: String
    likes: Int
    createdBy: User!
    messages: [Message]
}

# Message typeDef
type Message {
    _id: ID
    messageBody: String!
    messageDate: String
    messageUser: User!
}

# Token type of JWT token
type Token {
    token: String!
}

# Type for the infiniteScroll post page
type PostsPage {
    posts: [Post]
    hasMore: Boolean
}

# Built in query types
type Query {
    getCurrentUser: User
    getPosts: [Post]
    infiniteScrollPosts(pageNum: Int!, pageSize: Int!): PostsPage
}

# Built in mutation types
type Mutation {
    addPost(title: String!, imageUrl: String!, categories: [String]!, description: String!, creatorId: ID!): Post!
    signupUser(username: String!, email: String!, password: String!): Token
    signinUser(username: String!, password: String!): Token
}